name: My First Workflow

on:
  pull_request:
      branches:
        - feature-2 

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Message
        run: echo "pull  request?"
      