name: My First Workflow

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Message
        run: echo "Hello how are you ?"
      - name: list env
        run: printenv